---

- name: restart apache
  service: name=httpd state=restarted enabled=yes

- name: restart firewall
  service: name=firewalld state=restarted enabled=yes

- name: restart memcached
  service: name=memcached state=restarted enabled=yes

- name: restart mysql
  service: name=mariadb state=restarted enabled=yes